version: "3.9"
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: pruebaDTI
    ports:
      - "3899:1433"
    environment:
      SA_PASSWORD: "YourStrong!Pass123"
      ACCEPT_EULA: "Y"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
